name: Create GH release

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  push:
    branches:
      - "issue-#10"

jobs:
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: "Build multiplatform"
        run: make build-multiplatform

      - name: Set Variables
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          title: ${{ github.sha }}
          token: ${{ secrets.RELEASE_TOKEN }}
          name: $VERSION
          files: |
            bin/goker-darwin-amd64
            bin/goker-darwin-arm64
            bin/goker-freebsd-amd64
            bin/goker-freebsd-arm
            bin/goker-linux-amd64
            bin/goker-linux-arm
            bin/goker-linux-arm64
            bin/goker-windows-amd64
