name: Create GH release

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  push:
    branches:
      - "issue-#10"

jobs:
  Setup:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
  Build:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Build multiplatform"
        run: make build-multiplatform
  Tag:
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Tag
        uses: anothrNick/github-tag-action@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: minor
  Release:
    needs: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: $VERSION
          files: |
            bin/goker-darwin-amd64
            bin/goker-darwin-arm64
            bin/goker-freebsd-amd64
            bin/goker-freebsd-arm
            bin/goker-linux-amd64
            bin/goker-linux-arm
            bin/goker-linux-arm64
            bin/goker-windows-amd64
